### ISSUE TITLE
get_clips is not usable without clip_id

### ISSUE THREAD

**Issue by funfox1** [Teekeks/pyTwitchAPI#14]
Hi,

I am trying to get the list of clips of a streamer, from a game. I have the broadcaster ID and the game ID but no clip id (that's what i am looking for)

Reading the twitch api on https://dev.twitch.tv/docs/api/reference#get-clips i should be using "get_clips".
i read the sentence : "For a query to be valid, id (one or more), broadcaster_id, or game_id must be specified. You may specify only one of these parameters." just before the optional query parameter.

The python TwitchAPI doesn't let me go without the clip_id. When i try the call :
test = twitch.get_clips(broadcaster_id=streamer.get('to_id'),game_id=Game.get('id'),first=100,started_at=timeStart)

i get the error : 
TypeError: get_clips() missing 1 required positional argument: 'clip_id'

Is it a difference between the python Twitch API and the Twitch API or should i do this differently ?

**Comment by Teekeks** [comment]
Hi! This looks like a misstake on my part (twitch changed a bunch of requirements of parameters lately, looks like I Missed that one).

I will fix this but as a temporary workaround, you can hand in a empty list for clip_id like this:

`test = twitch.get_clips(streamer.get('to_id'), Game.get('id'), [], first=100, started_at=timeStart)`
