### ISSUE TITLE
Datetime.datetime not accepted "as is" as parameter in get_clips (for started_at)

### ISSUE THREAD

**Issue by funfox1** [Teekeks/pyTwitchAPI#15]
Hi again !

Still working on get_clips to try to get the list of clips of some streamers.

I used the temporary workaround you provide me to not use "clip_id"

test = twitch.get_clips(streamer.get('to_id'), Game.get('id'), [], first=100, started_at=timeStart)
I get an answer from twitch (no exception in the code) that is : 
{'error': 'Bad Request', 'status': 400, 'message': 'parsing time "2020-10-26T19:30:50.688906" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"'}

I tried using a timeStart generated by the two codes : 
timeStart = datetime.datetime(datetime.date.today().year, datetime.date.today().month, datetime.date.today().day)
timeStart = datetime.datetime.now()

Meaning my timeStart is coded : 2020-10-26 19:30:50.688906

Should the get_clips function "transform" the datetime.datetime given by adding something in the end before sending it to twitch? Or is there something i missed ? Or is the "Z07:00"  something that i can provide ? 

I tried playing with tznames from datetime but i can't find a way to make this work...

**Comment by Teekeks** [comment]
Hey! Thanks for this bug report. I am now aware what is going on there and have a workarround for you until I fix this with the next version:

`test = twitch.get_clips(streamer.get('to_id'), Game.get('id'), [], first=100, started_at=timeStart.astimezone())`

(from my tests: you also need to make sure that either broadcaster_id or game_id is None, they completly changed the requirements for this call).
