### ISSUE TITLE
Chat command prefix should be configurable

### ISSUE THREAD

**Issue by aw-was-here** [Teekeks/pyTwitchAPI#154]
It would be great to offer an option to configure another character besides ! as the prefix to commands.

**Comment by Teekeks** [comment]
As per twitch docs, bots should always use ! as a prefix, so not sure if I should add this.

 See here: https://dev.twitch.tv/docs/irc/send-receive-messages
 
 > If your bot accepts commands, the convention for third-party commands is to use an exclamation point (e.g., !dice). Using the forward slash or dot (e.g., /ban or .ban) is reserved for Twitch commands.

**Comment by Teekeks** [comment]
fair point, I think this could work when I explicitly dont allow / and .
