### ISSUE TITLE
get_broadcaster_subscriptions() returns an empty result

### ISSUE THREAD

**Issue by ThatHypedPerson** [Teekeks/pyTwitchAPI#163]
I was trying to use the method `get_broadcaster_subscriptions()` in my program to see the subscribers on my channel, but it always gave me a practically empty result.

I get an error when attempting to get any value from the `BroadcasterSubscriptions` object given by the `get_broadcaster_subscriptions()` method, along with its `to_dict()` method resulting in an empty dictionary.

I know it's not supposed to be empty as making a request via curl to the same endpoint ([as described by Twitch docs](https://dev.twitch.tv/docs/api/reference#get-broadcaster-subscriptions)) I get a proper result.

I may be dumb and just using it incorrectly, so I put some example code of what I was trying along with the result I get from each print statement.

```
#!/usr/bin/env python3

from twitchAPI.twitch import Twitch
from twitchAPI.oauth import UserAuthenticator
from twitchAPI.types import AuthScope
from twitchAPI.helper import first
import asyncio

async def main():
	twitch = await Twitch('my_app_id', 'my_app_secret')

	target_scope = [AuthScope.CHANNEL_READ_SUBSCRIPTIONS]
	auth = UserAuthenticator(twitch, target_scope, force_verify=False)
	
	token, refresh_token = await auth.authenticate()

	await twitch.set_user_authentication(token, target_scope, refresh_token)
	subscribers = await first(twitch.get_broadcaster_subscriptions(broadcaster_id="id"))
	print(type(subscribers))	# <class 'twitchAPI.object.BroadcasterSubscriptions'>
	print(subscribers.to_dict())	# {}
	print(subscribers.total)	# Exception: 'BroadcasterSubscriptions' object has no attribute 'total'
	
asyncio.run(main())
```

Any help with this would be appreciated.

**Comment by Teekeks** [comment]
Fix now available in v3.2.2
