### ISSUE TITLE
Question about the parameter of time.

### ISSUE THREAD

**Issue by jd0252** [Teekeks/pyTwitchAPI#165]
Hello,

I want to get videos from a specified Twitcher after 2022.

Here is my code:

start=twitchAPI.helper.datetime_to_str(start)
twitch.get_videos(user_id="user_id", after  =start)

I got an error message:
**TwitchAPIException: Bad Request - The cursor specified in the before or after query parameter is not valid.**

What is the correct form of the time parameter?

**Comment by Teekeks** [comment]
`after` is the parameter used for pagination (which you should most likely never need to touch in the new library version). You are probably looking for `period`.

More info in the documentation here:
https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.twitch.html#twitchAPI.twitch.Twitch.get_videos
