### ISSUE TITLE
Add HOSTTARGET event handler to Chat

### ISSUE THREAD

**Issue by Teekeks** [Teekeks/pyTwitchAPI#168]
HOSTTARGET is currently not implemented in Chat.

Add appropriate event and handler.

Docs:https://dev.twitch.tv/docs/irc/commands#hosttarget

**Comment by iProdigy** [comment]
Don't bother with this one; it's no longer sent since host mode is decommissioned

**Comment by Teekeks** [comment]
Oh! Good to know.
