### ISSUE TITLE
ChatRoom user list

### ISSUE THREAD

**Issue by Kodstok** [Teekeks/pyTwitchAPI#172]
Hello there , 

Just discovered this project and I'm wondering,  as twitch use a irc based chat it should be possible to collect all users connected to the chat, right ?

If yes could it be added ?

**Comment by Teekeks** [comment]
unfortunately twitch does not implement a full compatible IRC server and does not send a user list on certain conditions (I think also just not at all anymore soon-ish)

However they added the Get Chatters endpoint to the API which will give you a full list.
You can see the documentation for the endpoint implemented in this library here: https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.twitch.html#twitchAPI.twitch.Twitch.get_chatters

**Comment by Kodstok** [comment]
Yes but sadly you need moderators rights :/ 

But thank you for the quick respons 👍

**Comment by Teekeks** [comment]
Yes, its annoying but unfortunately nothing that can be changed :(
