### ISSUE TITLE
ChatMessage room property is not set 

### ISSUE THREAD

**Issue by Kodstok** [Teekeks/pyTwitchAPI#173]
On a  `ChatEvent.MESSAGE`  room property is not set.
Acording to : https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.chat.html#twitchAPI.chat.ChatMessage.room
room property is optional, but I know the message comes from a roomn, unfortunately I don't  now which one (and I need it)
What is the mechanisme behind this property being set or not ?

**Comment by Teekeks** [comment]
Its Null on a cache miss, so for example when your bot just joined and got a message before event before it got the notification (and with that the room details) that it joined.

It should be populated if you retry after something like half a second. (in reality closer to a few ms but that should do the trick)

**Comment by Teekeks** [comment]
Thinking about it, I know at least the name it came from when the message is issued so I should probably make that available.

**Comment by Teekeks** [comment]
when you get a cache miss like that, could you please look if all rooms are present in `msg.chat.room_cache`?
That variable should be a dictionary with the room names as keys and ChatRoom as value.

- Are all rooms present that you joined?
- is the value of any key in that cache None?

**Comment by Kodstok** [comment]
I've tried to join 42 room (some of them are offline) only 23 are present in msg.chat.room_cache and this number seems go down as the time pass

No value is set to None

**Comment by Teekeks** [comment]
Oh thats interesting, can you check if you get `ChatEvent.LEFT` events for those channels?

**Comment by Kodstok** [comment]
after adding 
`self.chat.register_event(ChatEvent.LEFT, self.room_left)`
and 
```Python
async def room_left(self, cht: ChatEvent):
        print("I LEFT A ROOM")
```
I can see it being trigered 51 times  juste before  `on_ready` function finish 

Then as before msg.chat.room_cache decrease  

and room_left is trigered time to time but always in burst 

> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM
> twitch_stats_1   | I LEFT A ROOM

**Comment by Teekeks** [comment]
Really interesting, thanks!
Will need to take a nook at that and try to reproduce it
