### ISSUE TITLE
Non-dynamic Redirect URI

### ISSUE THREAD

**Issue by EnochLucas** [Teekeks/pyTwitchAPI#18]
Hello,

I am currently trying to get the ouath section of this work. In order for this to work you must have a redirect URI for your site that is set inside the settings for your twitch site as you mention here: https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.oauth.html?highlight=redirect#requirements
However, I did not see a way for you to change the redirect URI, which means that the only valid redirect uri is 'localhost:17563' as seen here under the UserAuthenticator class: [https://github.com/Teekeks/pyTwitchAPI/blob/master/twitchAPI/oauth.py](url)

Did I miss something in the documentation? Or was there a way of directly changing the uri in the UserAuthenticator class?

**Comment by Teekeks** [comment]
Yes that is bad documentation from my side (and a bit of missing functionality).

UserAuthenticator has the attributes `url` and `port`
The final URL that has to be accessable is build here: https://github.com/Teekeks/pyTwitchAPI/blob/master/twitchAPI/oauth.py#L122

Which means: 

* Its forced to http only (will change that & make a new issue about that)
* you can change the localhost part to something else
* you can change the port

I will change it to the same system that the Webhook uses in a future update (you can set the full redirect URL and the port it listens to can be a different one to the one specified in the URL to allow for propper work with reverse proxies)

**Comment by EnochLucas** [comment]
Thanks for the quick reply!

Sounds good on the http change.
