### ISSUE TITLE
Add `py.typed` marker

### ISSUE THREAD

**Issue by Syndace** [Teekeks/pyTwitchAPI#197]
Hi,

it seems this library is fully typed, which is great, thanks!

However, your package does not seem to include the `py.typed` marker file, which is required to be PEP 561-compliant, and allow users of your library to type-check their code against your type annotations. The `py.typed` marker file is a simple empty file that you add to your root package, you can read about it here: https://peps.python.org/pep-0561/#packaging-type-information

**Comment by Syndace** [comment]
I'm afraid that didn't work, the `py.typed` file is not included in the new release on PyPI. I'm not sure why - maybe `setup.cfg` is used by the package build instead of `setup.py`?

**Comment by Teekeks** [comment]
the newest release does not include this commit yet

**Comment by Teekeks** [comment]
@Syndace now its in the new release (version 3.6.2)

**Comment by Syndace** [comment]
Thanks <3
