### ISSUE TITLE
AuthScope seems to be missing automod_settings (both read and update)

### ISSUE THREAD

**Issue by funkywaddle** [Teekeks/pyTwitchAPI#199]
The AuthScope class seems to be missing both 
`moderator:read:automod_settings`
and 
`moderator:manage:automod_settings`

Also, the methods for the endpoints needing those scopes:
[get-automod-settings](https://dev.twitch.tv/docs/api/reference/#get-automod-settings)
and
[update-automod-settings](https://dev.twitch.tv/docs/api/reference/#update-automod-settings)

**Comment by Teekeks** [comment]
seems like I also somehow missed those 2 endpoints
