### ISSUE TITLE
get_chatters() raises TypeError

### ISSUE THREAD

**Issue by Braastos** [Teekeks/pyTwitchAPI#225]
If the get_chatters() method is called with only broadcaster_id and moderator_id it raises an TypeError.

`
File "twitchAPI\twitch.py", line 3822, in get_chatters`
`if first is not None and first < 1 or first > 1000:`
`                                      ^^^^^^^^^^^^`
`TypeError: '>' not supported between instances of 'NoneType' and 'int'
`
My current workaround is setting first to 100.

**Comment by d7415** [comment]
Just need to clarify the `and` vs `or` (#226)
