### ISSUE TITLE
Is it possible to handle webhook requests using django redirections (without built-in aiohttp.web server) ?

### ISSUE THREAD

**Issue by RduMarais** [Teekeks/pyTwitchAPI#236]
Hi all, 

I am making a django application using pyTwitchAPI. 
I am trying to use EventSub, but from what I understand, the constructor creates a new server thread with aiohttp.web.Application.

**Is there a way to handle incoming request for event sub using my - already functioning - Django App ?**
The reason for this are : 
 * I would like to ship a complete and simple website, without having to tweak my nginx/apache/whatever configuration.
 * I would prefer not to open ports or advise to do so to keep a consistent security policy.

Do I have to use aiohttp.web.Application and open a port ?
Or can I call primitives of the eventsub class from a URL defined in django ?

Sorry for this quite django-specific question. If there is no simple way around, any help would be greatly appreciated !

Thanks a lot

**Comment by RduMarais** [comment]
I reckon this is the case for the authentication when creating a `twitchAPI.twitch.Twitch` object, and I implemented my authentication and callbacks accordingly.
But can I do the same for `twitchAPI.eventsub.EventSub` ? there should be no authentication going on in the EventSub, only the use of a token previously obtained, so I'm not sure that I understood your answer correctly

**Comment by stolenvw** [comment]
Yeah I totally miss read that, for eventsub I'm not sure of away around it for now, I know they are working on websockets for eventsub but don't know if that is out of beta yet

**Comment by Teekeks** [comment]
its not possible to do that at the moment, the websocket eventsub is also still in beta

**Comment by RduMarais** [comment]
Thansk, is there a way to only listen on localhost with the eventsub server then ?

**Comment by Teekeks** [comment]
yes, , the EventSub class has `_host` as a variable, setting that to `127.0.0.1` before calling `.start()` should do the trick. (I should really properly expose that var)

**Comment by Teekeks** [comment]
EventSub Websocket is now released and host of EventSub Webhook has been exposed.
