### ISSUE TITLE
Add new parameter to Twitch.get_channel_information

### ISSUE THREAD

**Issue by Teekeks** [Teekeks/pyTwitchAPI#240]
The following fields where added to the "Get Channel Information" Endpoint:
- [x] `is_branded_content`
- [x] `content_classification_labels`

https://dev.twitch.tv/docs/api/reference/#get-channel-information

**Comment by BarryCarlyon** [comment]
`ccl_locale` isn't valid for this endpoint, it was added to the documentation in error

**Comment by Teekeks** [comment]
Thanks, updated
