### ISSUE TITLE
HomeAssistant integration stopped working

### ISSUE THREAD

**Issue by bergdahl** [Teekeks/pyTwitchAPI#268]
This is due to the `get_users_follows()` API stopped working 3rd of August. I changed that call to use the `get_channel_followers` instead, but version 3.12.0 does not contain commit 26f2126 which is needed for this to work, as it requires MODERATOR_READ_FOLLOWERS scope.

Can we get a new version release so I can fix the HA integration please?

**Comment by Teekeks** [comment]
would a RC do it? only thing thats gonna change till the full release will be documentation and maybe some code usefull for mocking, should not impact anything used by HA

**Comment by bergdahl** [comment]
I already tested that the commit works, but HA needs to get it from pypi. Thus the need for a new release.

**Comment by Teekeks** [comment]
v4.0.0 is now available via pypi
