### ISSUE TITLE
[Question] 1 Time Authentication

### ISSUE THREAD

**Issue by ftk789** [Teekeks/pyTwitchAPI#281]
Is it possible to make it only Authentication once? Instead of it opening the Auth link everytime I execute the python script?

**Comment by Teekeks** [comment]
Yes, you can use `UserAuthenticationStorageHelper` (or implement such a mechanic on your own) to keep a token between program restarts.

I wrote a tutorial here: https://pytwitchapi.dev/en/latest/tutorial/reuse-user-token.html

**Comment by ftk789** [comment]
> Yes, you can use `UserAuthenticationStorageHelper` (or implement such a mechanic on your own) to keep a token between program restarts.
> 
> I wrote a tutorial here: https://pytwitchapi.dev/en/latest/tutorial/reuse-user-token.html

Oh my god, What a fast reply, Thank you very much, I didn't know there was a Storage Helper by you, Thank you very much <3
