### ISSUE TITLE
EventSub stop() RuntimeError difference between Webhook and Websocket

### ISSUE THREAD

**Issue by Braastos** [Teekeks/pyTwitchAPI#285]
I noticed that the EventSubWebsocket stop method can raise a RuntimeError when called, while its not running.
EventSubWebhook wont raise this Error.
The RuntimeError in EventSubWebsocket.stop() is not documented at the moment.
Additionally its documented that the stop method automatically unsubscribes from all known subscriptions if unsubscribe_on_stop is true, but in EventSubWebsocket there is no unsubscribe_on_stop or code to handle unsubscribing on stop. I don't know if this is handled elsewhere (or not needed), because Twitch does things differently for Websockets.

**Comment by Teekeks** [comment]
For Websockets, all subscriptions will automatically dropped. Will fix the inconsistency with the Runtime Exception
