### ISSUE TITLE
Subloggers not set properly

### ISSUE THREAD

**Issue by Julian-O** [Teekeks/pyTwitchAPI#314]
In each of [twitchAPI/eventsub/websocket.py](https://github.com/Teekeks/pyTwitchAPI/blob/c2053b8529da57aad5c5d8d0d651ab61ee956f5d/twitchAPI/eventsub/websocket.py#L146) and [twitchAPI/eventsub/webhook.py](https://github.com/Teekeks/pyTwitchAPI/blob/c2053b8529da57aad5c5d8d0d651ab61ee956f5d/twitchAPI/eventsub/webhook.py#L150) there is a line of the form:

     self.logger.name = 'twitchAPI.eventsub.<blah>'
     
This is not the correct way to select to use a sublogger. The [logging documents](https://docs.python.org/3/library/logging.html) explicitly state that the `name` attribute should be considered to be read-only.

The consequence is that it is impossible to filter messages from this sublogger (which is how I noticed it).

The correct way is of the form:

    self.logger = logging.getLogger("twitchAPI.eventsub.<blah>")

**Comment by Teekeks** [comment]
Thanks for the report!
