### ISSUE TITLE
twitch.py wrong URL in channel point subroutines

### ISSUE THREAD

**Issue by asphaltschneider** [Teekeks/pyTwitchAPI#46]
Hi,

I found a bug inside of twitch.py.

The subroutines:
- delete_custom_reward
- get_custom_reward
- get_custom_reward_redemption
- update_redemption_status
are missing the TWITCH_API_BASE_URL inside the call of the build_url function.

At the moment they are defined as:
url = build_url('channel_poi......
but should look like:
url = build_url(TWITCH_API_BASE_URL + 'channel_poi......

Could you please fix that?

regards
Thomas

**Comment by Teekeks** [comment]
Yes, I will fix this and push a update within a few hours, thanks for the find!
