### ISSUE TITLE
get_clips with more than 100 clips ? Can't use cursor

### ISSUE THREAD

**Issue by funfox1** [Teekeks/pyTwitchAPI#56]
Hi ! 

I am trying to use get_clips again, to get a list of all clips done on twitch about one game during a duration.

exemple : 
startDate = datetime.datetime(datetime.date.today().year, datetime.date.today().month, datetime.date.today().day)
test = twitch.get_clips(game_id=505705,first=100,started_at=startDate.astimezone())

The result can get bigger than 100 clips, and Twitch API limits to 100 clips the response. But there is a data called 'pagination' at the end of the response that is supposed to let me "start the next query from there".

https://dev.twitch.tv/docs/api/reference#get-clips : 
pagination | object containing a string | A cursor value, to be used in a subsequent request to specify the starting point of the next set of results.

The V5 Twitch API was more explicit about this, and the "Get Top Clips" had a "cursor" defined as optional query parameter
(https://dev.twitch.tv/docs/v5/reference/clips).
The latest twitch API doesn't list "cursor" or "pagination" as an optional query parameter, but i suppose it should, else i can't get the next 100 clip batch. And in this case the pagination in the response would be useless. 

Is it possible to check if the Twitch API accept a pagination object in the query, and if yes, to add this in the get_clips function ?

Thanks in advance !

funfox

**Comment by Teekeks** [comment]
The Parameter `after` of get_clips is the forward pagination parameter. For backward pagination use `before` (this is analog to the documentation of Twitch.

Just set the `after` Parameter to the value you get from the pagination.

**Comment by funfox1** [comment]
OMG i am so sorry i didn't understand it at the first glance !
