### ISSUE TITLE
Twitch doesn't register webhook subscription

### ISSUE THREAD

**Issue by NikitaCartes** [Teekeks/pyTwitchAPI#6]
I want to subscribe to stream changes and I use slightly modded of webhook_example.py:
```
twitch = Twitch(APP_ID, APP_SECRET)
twitch.authenticate_app([])

hook = TwitchWebHook("https://nikitacartes.xyz:8100/", APP_ID, 8101)
hook.authenticate(twitch.get_app_token())
hook.start()

success, uuid_stream = hook.subscribe_stream_changed(USER_ID, callback_stream_changed)

print(f'was subscription successfull?: {success}')
print(twitch.get_webhook_subscriptions())
```

But get_webhook_subscriptions says, what i have 0 subscription.

```
was subscription successfull?: True
{'total': 0, 'data': [], 'pagination': {}}
```

For proxy from 8100 port to Plain 8101 I use maproxy, if this is important. 
```
import tornado.ioloop
import maproxy.proxyserver

ssl_certs = {"certfile":  "nikitacartes.xyz/fullchain.pem", "keyfile": "nikitacartes.xyz/privkey.pem"}

server = maproxy.proxyserver.ProxyServer("0.0.0.0", 8101, client_ssl_options=ssl_certs)
server.listen(8100)
tornado.ioloop.IOLoop.instance().start()
```

**Comment by NikitaCartes** [comment]
```
success, uuid_stream = hook.subscribe_stream_changed('117871161', callback_stream_changed)
sleep(2)
print(f'was subscription successfull?: {success}')
print(twitch.get_webhook_subscriptions())

input('Press enter to stop...')

print(twitch.get_webhook_subscriptions())
```
0 subscribes after 2 seconds sleep and after ~60 seconds wait before input.

**Comment by Teekeks** [comment]
Then it might be due to how you set up the proxy. I will test that one, I usually use a reverse proxy from nginx

**Comment by NikitaCartes** [comment]
Thank you.
Then I guess I'll try nginx and report back my results

**Comment by Teekeks** [comment]
This is a example working nginx config:
`server {
    server_name my-cool.domain.com;
    access_log  off;
    error_log   off;
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/my-cool.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my-cool.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_pass      http://127.0.0.1:9765/;
        proxy_redirect  off;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_max_temp_file_size 0;

        client_max_body_size       10m;
        client_body_buffer_size    128k;

        proxy_connect_timeout      90;
        proxy_send_timeout         90;
        proxy_read_timeout         90;

        proxy_buffer_size          4k;
        proxy_buffers              4 32k;
        proxy_busy_buffers_size    64k;
        proxy_temp_file_write_size 64k;
    }


}`

**Comment by spigot** [comment]
subscribing and unsubscribing was working ... about a week ago? but I'm having the same issue- I get a True returned for success for my actions, but my subscriptions don't change. I copied your nginx proxy settings verbatim, and tried adding the sleep.

**Comment by Teekeks** [comment]
The True is from the initial handshake (aka you are permitted to request this webhook), there is an additional handshake taking place after which the webhook will be active. if this handshake fails for some reason (for example your webhook not being reachable due to a invalid ssl certificate), you will get a true but not a working webhook.

I am currently working on adding some more tooling for this and other webhook related functions. It will probably release at the end of this week or soon after that.

**Comment by Teekeks** [comment]
I adressed the return true when failing in the current 2.0 development.
