### ISSUE TITLE
Add option to use UserAuthenticator in a server enviroment

### ISSUE THREAD

**Issue by Teekeks** [Teekeks/pyTwitchAPI#62]

**Comment by rubrodapa** [comment]
Hi Teekeks! I started using your library and I really like it. I have changed the UserAuthenticator so it can be used with a REST API backend. Maybe that will apply to this issue? If that's the case I can make a PR if you are ok with it.

**Comment by Teekeks** [comment]
This sounds like a awesome PR, please do

**Comment by Teekeks** [comment]
PR was merged
