### ISSUE TITLE
FileNotFound oauth.htlm when creating an .exe with pyinstaller

### ISSUE THREAD

**Issue by Kenshin9977** [Teekeks/pyTwitchAPI#66]
OS: Windows 10

When I authenticate using auth.authenticate() I should be redirected to oauth.html. It works when I test my code within pycharm but it doesn't when I run an .exe created with pyinstaller.

The command line I used to create the .exe :
`pyinstaller --onefile main.py`

The error I get :
```
Error handling request
Traceback (most recent call last):
  File "lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
  File "lib\site-packages\aiohttp\web_app.py", line 499, in _handle
  File "lib\site-packages\twitchAPI\oauth.py", line 230, in __handle_callback
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Kenshin\\AppData\\Local\\Temp\\_MEI148602\\twitchAPI\\oauth.html'
```

If I create an .exe without the --onefile option I can workaround the issue by placing oauth.html within .\dist\twitchAPI\.

**Comment by Teekeks** [comment]
Seems like pyinstaller is ignoring the file, will investigate

**Comment by Kenshin9977** [comment]
I still have the same issue on the latest version (2.5.1)

**Comment by Teekeks** [comment]
@Kenshin9977 this exact problem? that should no longer happen since that file does not even exist in the current version of the library
