### ISSUE TITLE
Question: How to check if a stream is online?

### ISSUE THREAD

**Issue by ibex-are-goats** [Teekeks/pyTwitchAPI#69]
Great work on this project! The documentation is very professional. Unfortunately I couldn't find how to check if a user's stream is online. 

My final goal is to check online status in a loop pretty rarely, say every minute, then keep checking, and then when they go offline, download the latest replay. So I'm looking over the internet trying to decide how to check if they're online...

**Comment by jjnilton** [comment]
Maybe you could use the [get_streams](https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.twitch.html#twitchAPI.twitch.Twitch.get_streams) and [get_stream_markers](https://pytwitchapi.readthedocs.io/en/latest/modules/twitchAPI.twitch.html#twitchAPI.twitch.Twitch.get_stream_markers) methods, passing the user(s) you want to check.

**Comment by portalthree** [comment]
I use a similar process in https://github.com/portalthree/pyTweetch to send a tweet when a user goes live, maybe you could try and adapt that code to your needs?

**Comment by chillymosh** [comment]
I would have said use the webhooks in pyTwitchAPI but they have been discontinued by Twitch now.
That would have sent you a message whenever a stream goes offline / online.
The new way to do it is with eventsubs which you the creator is currently working on implementing into this library.

You could possibly use some of the current features of this and build your own eventsub functions based on top of it using the Twitch API docs or wait for the update.

**Comment by Teekeks** [comment]
EventSub is now implemented and with it you get access to this topic: https://pytwitchapi.readthedocs.io/en/v2.4.0/modules/twitchAPI.eventsub.html#twitchAPI.eventsub.EventSub.listen_stream_online

**Comment by ibex-are-goats** [comment]
@Teekeks Sorry to bother you about this again, but I've been tinkering with this on and off, and it's still above my skill level! :D 

Is there a way to check for stream online/offline WITHOUT running the web server, having the client authenticate with me, and so on? Or, put another way, are there any functions left that don't require Twitch's new restrictions, so they can be run by anyone, anytime? 

Thanks :)

**Comment by chillymosh** [comment]
Eventsub currently requires a webserver and a publicly accessible URL to send the webhook to, with SSL that you own, until  Twitch release the websocket version out of beta.

The only other option is to poll the endpoint.

**Comment by Teekeks** [comment]
@chillymosh The webhook version is already in a beta? thats good to hear.
But yes, there is currently no way other than eventsub with the mentioned requirements or periodically polling the endpoint.

**Comment by chillymosh** [comment]
The websocket version is currently in closed beta to select bot creators.

**Comment by Braastos** [comment]
Phantombot uses for online detection an unofficial topic ("video-playback-by-id") in pubsub, not sure if you can use this.

**Comment by ibex-are-goats** [comment]
> poll the endpoint

I'm guessing by "endpoint" you mean the video stream itself? So, do some HTML/web magic to try to play the video, and if that doesn't work, it's offline? I think that out of my expertise, but I'm going to keep picking away at things. 

Upon further research, I think I can do basically that by using one of the downloader/playing apps. I just tried mpv, streamlink, and youtubedl, and they all play a stream but fail if they can't. So in theory, one can just use one of them to hammer a stream until there's a successful result. Streamlink even has a Python API, so streamlink.streams(url) returns video links if online, and nothing if offline. That said, maybe the actual online check is 10 lines of code and doesn't demand a library, so I'll keep looking :D 

Keep up the good work everyone. I hope Twitch stays and/or gets more developer-friendly.

**Comment by iProdigy** [comment]
Endpoint refers to helix's official "Get Streams" method (which requires oauth to use): https://dev.twitch.tv/docs/api/reference#get-streams
