### ISSUE TITLE
WebSub doesn't seem to be working anymore

### ISSUE THREAD

**Issue by jjnilton** [Teekeks/pyTwitchAPI#70]
Hi, thanks for sharing the library.

When subscribing I get the following message (even though I'm using the application for more than one week now):

> Subscription failed! status code: 404, body: {"error":"Not Found","status":404,"message":"WebSub is deprecated and will be shutdown on September 16, 2021. Applications that have not accessed WebSub before June 16, 2021 no longer have access to WebSub. Consider using EventSub for Webhooks instead. For more information on the WebSub shutdown plan, see https://discuss.dev.twitch.tv/t/deprecation-of-websub-based-webhooks and the EventSub documentation at https://dev.twitch.tv/docs/eventsub."}

**Comment by Teekeks** [comment]
Please switch to EventSub: https://pytwitchapi.readthedocs.io/en/v2.4.0/modules/twitchAPI.eventsub.html#
