### ISSUE TITLE
Question on EventSub

### ISSUE THREAD

**Issue by Daenara** [Teekeks/pyTwitchAPI#83]
Evening,

I am switching over to EventSub today since webhooks were taken down yesterday and i did not find the time to do so before. My old system checked if the webhook was created successfully, here EventSub throws an exception if I understood it right, and there are no more uuids to handle, but the listen functions still return a string. I could not find what this string does/is needed for. My guess is, that it returns the topic_id needed to unsubscribe, but I would love if someone could confirm this guess (or tell me what it is if it isn't this).

Also, it might be a good thing to add to the documentation.

Daenara

**Comment by Teekeks** [comment]
The string returned is a uuid generated by twitch for your subscription. You dont need to keep it unless you use it to check which event called your callback function (in case you reuse the same function) of if you want to specifically stop to listen to that specific subscription.
So yes this is the topic_id.

**Comment by Daenara** [comment]
Thanks for clarification. Since I actually listen to events for multiple channels, I need a way to unsubscribe everything for one channel, so having the topic_id returned is great.
