### ISSUE TITLE
Make it possible to subscribe the same EventSub event on multiple streams

### ISSUE THREAD

**Issue by Daenara** [Teekeks/pyTwitchAPI#84]
Evening, me again...

I have been trying to adapt my bot/webserver/twitch helper to event subs and I ran into a bit of a problem. I need to monitor multiple streams at once, and now I get an error thrown when I register the event a 2nd time. With webhooks this worked fine, I just had to track which uuid belonged to wich stream, but now I would need a whole new api listener per stream which means one port per stream, and this is something I can't dynamically change on runtime.

Would it be possible to allow multiple listeners per event like it was with webhooks?

Here a bit more about why I need what I am asking for. My python app is a mixture of twitch bot and webserver serving notification alerts to obs. When I started writing this, my friends were interested, and I made it possible to work with more than one stream. I have one bot listening to multiple channels, I have one webserver serving multiple streams on different sub urls and until now I had one twitch api listener that was filling my custom stream objects with information that the bot and the webserver then use to do their thing. But now the exception prevents me from doing it.

I get throwing an exception if it is completely the same, but if I try to listen to two different streams, then it should be possible.

**Comment by Teekeks** [comment]
I am guessing you are talking about the EventSubSubscriptionConflict exception? You only get that if you try to register 2 listener for the same event with the same conditions (eg trying to listen to listen_channel_follow 2x for the same streamer), if you specify a different condition, this will work fine.

If you mean a different error then I would need the exact error you get when trying to register your listener.

**Comment by Daenara** [comment]
Consider me stupid. After staring at it a while I found that I called listen_stream_online twice instead of one being offline. I changed that at least 20 times today, but it seems one undo or another added this back in. Because it ran fine when I tried it on one channel, and the error occurred when I tried it on two channels, I though it to be thrown even when streams differ, but apparently I added the bug back in somehow. I have been trying to get this to run for 3 hours now, and my brain seems to have stopped working somewhere in between.

**Comment by ria4** [comment]
@Daenara You might want to have a look at a Telegram bot I wrote upon this library. It seems it's doing mostly what you're trying to do, including keeping track of multiple uuids (even though in the end it's for a Telegram bot and not a Twitch one).

https://github.com/ria4/lajujabot/blob/46c8599600e832fe67cd583a23705e8e5575f843/bot.py#L112

**Comment by Daenara** [comment]
@ria4 I do have a working program, I was just tired and somehow managed to add in the same bug around 6 times in total, without noticing it. Originally, I was using webhooks, so I only messed up a bit on the conversion to EventSub.

Only thing I am still really struggling with is shutting the whole thing down gracefully, and that is just me needing to wrap my head around asyncio. I can run for days on end without problem, but shutting down always ends with one exception or another

**Comment by Teekeks** [comment]
the part of the library should gracefulyl shut down if you call the stop() function, if its not doing that please open a new issue with the full erro message and a code example to replicate the issue

**Comment by Daenara** [comment]
Not a problem with your library, more with stopping my run forever loop after all the async stop functions managed to run through. I can't wait for them because the signal exit handler can't be async, and the functionality to add an exit handler to a loop directly is not implemented in 3.7, I tried that. Current approach is create tasks, stop the loop and run another loop to continue the tasks but the first loop just won't stop when I want it to, so I live with it throwing an exception.

**Comment by Teekeks** [comment]
You can take a look at what my stop function is doing, the library also just uses a run_forever() to keep running in its own thread
