### ISSUE TITLE
Add endpoints for banning / unbanning

### ISSUE THREAD

**Issue by pixelsuchter** [Teekeks/pyTwitchAPI#94]
It would be nice to have these endpoints available for making a tool to mass ban or unban accounts. Going through my 1 million name bot account list is not really doable over IRC.

**Comment by Teekeks** [comment]
I plan to add them as soon as they leave the beta phase

**Comment by Braastos** [comment]
Any ETA for this?

**Comment by Teekeks** [comment]
added in e10037bc2fbb73600fd7e0d2ec9ef01d61b97048 and 123198d924d82e3522ea50f6d4a8e8f3209b9d72
