### ISSUE TITLE
Different "internal" and "external" port

### ISSUE THREAD

**Issue by DaryeDev** [Teekeks/pyTwitchAPI#98]
I'm using jprq to tunnel my localhost outside of lan, exposing the my port 4047, but it ends up being another number outside. 
How can I set it to listen on 4047 for eventsub confirmation and set the callback to the other number?

**Comment by d7415** [comment]
From the example
```py
hook = EventSub(WEBHOOK_URL, APP_ID, 8080, twitch)
```
you can replace 8080 with the port you want to listen on internally, and set any external port in the `WEBHOOK_URL` string.

**Comment by d-fischer** [comment]
EventSub does not support any port other than 443 (on Twitch's side for the external URL), so that's what the library *should* already use to register callbacks with Twitch.

**Comment by d7415** [comment]
> EventSub does not support any port other than 443

Ah, my bad. Maybe I got confused with auth callbacks. But I think the library just registers the URL as given (which would imply 443 for an https URL if not otherwise specified)

**Comment by DaryeDev** [comment]
> > EventSub does not support any port other than 443
> 
> Ah, my bad. Maybe I got confused with auth callbacks. But I think the library just registers the URL as given (which would imply 443 for an https URL if not otherwise specified)

On Twitch's API Docs it says this: 
> Your callback must use SSL and listen on port 443
Which is weird, because I'm supposedly using with Ngrok on port 4047...

**Comment by DaryeDev** [comment]
> From the example
> 
> ```python
> hook = EventSub(WEBHOOK_URL, APP_ID, 8080, twitch)
> ```
> 
> you can replace 8080 with the port you want to listen on internally, and set any external port in the `WEBHOOK_URL` string.

This approach returns this as an Exception: `callback must provide valid https callback with standard port in creation request`

**Comment by d7415** [comment]
> This approach returns this as an Exception: `callback must provide valid https callback with standard port in creation request`

Yes, as @d-fischer pointed out, Twitch requires HTTPS on the standard port (443) for EventSub.

> Which is weird, because I can register all events correctly with Ngrok on port 4047...

Is Ngrok listening on 443 then redirecting to 4047 internally?

**Comment by DaryeDev** [comment]
> Is Ngrok listening on 443 then redirecting to 4047 internally?

I have no idea, but I might stick to ngrok for the moment...
